import streamlit as st
import snowflake.connector
import pandas as pd
import re

# ---------------------------
# CONFIG
# ---------------------------
st.set_page_config(page_title="AI Data Analyst", layout="wide")

# ---------------------------
# CONNECTION
# ---------------------------
@st.cache_resource
def init_connection():
    return snowflake.connector.connect(
        user=st.secrets["SNOWFLAKE_USER"],
        password=st.secrets["SNOWFLAKE_PASSWORD"],
        account=st.secrets["SNOWFLAKE_ACCOUNT"],
        warehouse=st.secrets["SNOWFLAKE_WAREHOUSE"],
        database=st.secrets["SNOWFLAKE_DATABASE"],
        schema=st.secrets["SNOWFLAKE_SCHEMA"]
    )

conn = init_connection()

# ---------------------------
# QUERY EXECUTION
# ---------------------------
def run_query(query):
    cursor = conn.cursor()
    try:
        cursor.execute(query)
        df = pd.DataFrame(cursor.fetchall(), columns=[col[0] for col in cursor.description])
        return df
    finally:
        cursor.close()

# ---------------------------
# CLEAN SQL
# ---------------------------
def clean_sql(text):
    text = text.replace("`", "").replace("\\", "").strip()
    select_index = text.lower().find("select")
    if select_index == -1:
        raise Exception("No valid SQL found from AI")
    sql = text[select_index:]
    sql = re.split(r";|\n\n", sql)[0]
    return sql.strip()

# ---------------------------
# FAST PATH FOR REVIEWS
# ---------------------------
def fast_path_reviews(question):
    q = question.lower()

    # Extract number from question (default to 1)
    count_match = re.search(r'\b(\d+)\b', q)
    count = int(count_match.group(1)) if count_match else 1

    if "random" in q and "review" in q:
        for i in range(1, 6):
            if f"{i} star" in q or f"{i}-star" in q:
                return f"""
                SELECT review_comment_message, review_score
                FROM AI_ANALYTICS_DB.GOLD.FACT_REVIEWS
                WHERE review_score = {i}
                AND review_comment_message IS NOT NULL
                ORDER BY RANDOM()
                LIMIT {count}
                """
        # No specific star rating mentioned — fetch any reviews
        return f"""
        SELECT review_comment_message, review_score
        FROM AI_ANALYTICS_DB.GOLD.FACT_REVIEWS
        WHERE review_comment_message IS NOT NULL
        ORDER BY RANDOM()
        LIMIT {count}
        """

    if "how many" in q and "review" in q:
        for i in range(1, 6):
            if str(i) in q:
                return f"""
                SELECT COUNT(*) AS total_reviews
                FROM AI_ANALYTICS_DB.GOLD.FACT_REVIEWS
                WHERE review_score = {i}
                """

    if "average" in q and "review" in q:
        return """
        SELECT AVG(review_score) AS avg_rating
        FROM AI_ANALYTICS_DB.GOLD.FACT_REVIEWS
        """

    return None
# ---------------------------
# GENERATE SQL
# ---------------------------
def generate_sql(question):
    prompt = f"""
    You are an expert Snowflake SQL generator.

    STRICT RULES:
    - ONLY return SQL starting EXACTLY with SELECT
    - DO NOT include ANY words before SELECT
    - DO NOT include phrases like "The query is"
    - Output must start with SELECT and end with a valid SQL statement
    - DO NOT include any additional text or explanations
    - Use only given tables
    - Always include review_score when selecting from FACT_REVIEWS

    DATABASE: AI_ANALYTICS_DB
    SCHEMA: GOLD

    TABLES:
    FACT_SALES(order_id, product_id, customer_id, order_date, price, freight_value)
    DIM_PRODUCTS(product_id, product_category_name)
    CUSTOMER_REVENUE(customer_id, total_spent, total_orders)
    MONTHLY_SALES(year, month, revenue)
    FACT_REVIEWS(order_id, review_score, review_creation_date, review_comment_message)
    
    QUESTION:
    {question}
    """
    cortex_query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        $$ {prompt} $$
    );
    """
    df = run_query(cortex_query)
    return clean_sql(df.iloc[0, 0])

# ---------------------------
# FIX SQL
# ---------------------------
def fix_sql(question, bad_sql, error):
    prompt = f"""
    Fix this SQL query.
    Error:
    {error}
    Bad SQL:
    {bad_sql}
    Return only SQL.
    """
    query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        $$ {prompt} $$
    );
    """
    df = run_query(query)
    return clean_sql(df.iloc[0, 0])

# ---------------------------
# EXECUTION
# ---------------------------
def execute_with_retry(question):
    sql = generate_sql(question)
    if not sql.lower().startswith("select"):
        raise Exception("Invalid SQL generated by AI")
    try:
        df = run_query(sql)
        return sql, df
    except Exception as e:
        fixed_sql = fix_sql(question, sql, str(e))
        df = run_query(fixed_sql)
        return fixed_sql, df

# ---------------------------
# SUMMARY
# ---------------------------
def generate_summary(question, df):
    if df.empty:
        return "No data found."
    data_sample = df.head(5).to_string(index=False)
    prompt = f"""
    Answer the question in one simple sentence.
    Question: {question}
    Data:
    {data_sample}
    """
    query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        $$ {prompt} $$
    );
    """
    df2 = run_query(query)
    return df2.iloc[0, 0].strip()

# ---------------------------
# SENTIMENT WORD BY STAR RATING
# ---------------------------
def analyze_sentiment(score):
    if score in [1, 2]:
        return "Negative"
    elif score == 3:
        return "Neutral"
    elif score in [4, 5]:
        return "Positive"
    else:
        return "Unknown"

# ---------------------------
# MEANING FROM REVIEW TEXT
# ---------------------------
def get_meaning(review_text):
    prompt = f"""
    Summarize this customer review in one simple sentence explaining what the customer means.
    Review: "{review_text}"
    Return only the summary sentence, no extra text.
    """
    query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        $$ {prompt} $$
    );
    """
    df = run_query(query)
    return df.iloc[0, 0].strip()

# ---------------------------
# UI
# ---------------------------
st.title("AI Data Analyst")

if "history" not in st.session_state:
    st.session_state.history = []

question = st.text_input("Ask your question")

if question:
    try:
        with st.spinner("Thinking..."):
            fast_sql = fast_path_reviews(question)

            if fast_sql:
                sql = fast_sql
                df = run_query(sql)
            else:
                sql, df = execute_with_retry(question)

            tab1, tab2, tab3 = st.tabs(["SQL", "Results", "Insight"])

            with tab1:
                st.code(sql)

            with tab2:
                st.subheader("Data Results")
                st.dataframe(df, use_container_width=True, hide_index=True)

                is_review_question = "review" in question.lower()

                if is_review_question and "REVIEW_COMMENT_MESSAGE" in df.columns and "REVIEW_SCORE" in df.columns:
                    st.divider()
                    st.subheader("Advanced Review Analysis")

                    # Remove star rating references before extracting count
                    cleaned_question = re.sub(r'\b([1-5])\s*[-]?\s*star', '', question.lower())
                    count_match = re.search(r'\b(\d+)\b', cleaned_question)
                    count = int(count_match.group(1)) if count_match else len(df)

                    active_reviews = df[["REVIEW_COMMENT_MESSAGE", "REVIEW_SCORE"]].dropna(subset=["REVIEW_COMMENT_MESSAGE"]).head(count)

                    review_contents = []
                    sentiments = []
                    meanings = []

                    for _, row in active_reviews.iterrows():
                        review_contents.append(row["REVIEW_COMMENT_MESSAGE"])
                        sentiments.append(analyze_sentiment(int(row["REVIEW_SCORE"])))
                        meanings.append(get_meaning(row["REVIEW_COMMENT_MESSAGE"]))

                    sentiment_df = pd.DataFrame({
                        "Review Content": review_contents,
                        "Sentiment": sentiments,
                        "Meaning": meanings
                    })

                    st.dataframe(sentiment_df, use_container_width=True, hide_index=True)
            
            with tab3:
                st.success(generate_summary(question, df))

            st.session_state.history.append((question, sql))

    except Exception as e:
        st.error(str(e))

# ---------------------------
# SIDEBAR
# ---------------------------
st.sidebar.title("History")
for q, s in reversed(st.session_state.history):
    st.sidebar.write(q)
    st.sidebar.code(s)