import streamlit as st
import snowflake.connector
import pandas as pd
import re

# ---------------------------
# CONFIG
# ---------------------------
st.set_page_config(page_title="AI Data Analyst", layout="wide")

# ---------------------------
# CONNECTION
# ---------------------------
@st.cache_resource
def init_connection():
    return snowflake.connector.connect(
        user=st.secrets["SNOWFLAKE_USER"],
        password=st.secrets["SNOWFLAKE_PASSWORD"],
        account=st.secrets["SNOWFLAKE_ACCOUNT"],
        warehouse=st.secrets["SNOWFLAKE_WAREHOUSE"],
        database=st.secrets["SNOWFLAKE_DATABASE"],
        schema=st.secrets["SNOWFLAKE_SCHEMA"]
    )

conn = init_connection()

# ---------------------------
# QUERY EXECUTION
# ---------------------------
def run_query(query):
    cursor = conn.cursor()
    try:
        cursor.execute(query)
        df = pd.DataFrame(cursor.fetchall(), columns=[col[0] for col in cursor.description])
        return df
    finally:
        cursor.close()

# ---------------------------
# CLEAN SQL
# ---------------------------
def clean_sql(text):
    text = text.replace("`", "").replace("\\", "").strip()

    # Find SELECT keyword
    select_index = text.lower().find("select")

    if select_index == -1:
        raise Exception("No valid SQL found from AI")

    # Extract ONLY SQL part
    sql = text[select_index:]

    # Remove trailing junk after query
    sql = re.split(r";|\n\n", sql)[0]

    return sql.strip()

# ---------------------------
# FAST PATH FOR REVIEWS
# ---------------------------
def fast_path_reviews(question):
    q = question.lower()
    if "random" in q and "review" in q:
        for i in range(1, 6):
            if str(i) in q:
                return f"""
                SELECT review_comment_message
                FROM AI_ANALYTICS_DB.GOLD.FACT_REVIEWS
                WHERE review_score = {i}
                AND review_comment_message IS NOT NULL
                ORDER BY RANDOM()
                LIMIT 1
                """

    if "how many" in q and "review" in q:
        for i in range(1, 6):
            if str(i) in q:
                return f"""
                SELECT COUNT(*) AS total_reviews
                FROM AI_ANALYTICS_DB.GOLD.FACT_REVIEWS
                WHERE review_score = {i}
                """

    if "average" in q and "review" in q:
        return """
        SELECT AVG(review_score) AS avg_rating
        FROM AI_ANALYTICS_DB.GOLD.FACT_REVIEWS
        """

    return None

# ---------------------------
# GENERATE SQL
# ---------------------------
def generate_sql(question):
    prompt = f"""
    You are an expert Snowflake SQL generator.


    STRICT RULES:
    - ONLY return SQL starting EXACTLY with SELECT
    - DO NOT include ANY words before SELECT
    - DO NOT include phrases like "The query is"
    - Output must start with SELECT and end with a valid SQL statement
    - DO NOT include any additional text or explanations
    - Use only given tables

    DATABASE: AI_ANALYTICS_DB
    SCHEMA: GOLD

    TABLES:
    FACT_SALES(order_id, product_id, customer_id, order_date, price, freight_value)
    DIM_PRODUCTS(product_id, product_category_name)
    CUSTOMER_REVENUE(customer_id, total_spent, total_orders)
    MONTHLY_SALES(year, month, revenue)
    FACT_REVIEWS(order_id, review_score, review_creation_date, review_comment_message)
    
    QUESTION:
    {question}
    """
    cortex_query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        $$ {prompt} $$
    );
    """
    df = run_query(cortex_query)
    return clean_sql(df.iloc[0, 0])

# ---------------------------
# FIX SQL
# ---------------------------
def fix_sql(question, bad_sql, error):
    prompt = f"""
    Fix this SQL query.
    Error:
    {error}
    Bad SQL:
    {bad_sql}
    Return only SQL.
    """
    query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        $$ {prompt} $$
    );
    """
    df = run_query(query)
    return clean_sql(df.iloc[0, 0])

# ---------------------------
# EXECUTION
# ---------------------------
def execute_with_retry(question):
    sql = generate_sql(question)
    if not sql.lower().startswith("select"):
        raise Exception("Invalid SQL generated by AI")

    try:
        df = run_query(sql)
        return sql, df
    except Exception as e:
        fixed_sql = fix_sql(question, sql, str(e))
        df = run_query(fixed_sql)
        return fixed_sql, df

# ---------------------------
# SUMMARY
# ---------------------------
def generate_summary(question, df):
    if df.empty:
        return "No data found."
    data_sample = df.head(5).to_string(index=False)

    prompt = f"""
    Answer the question in one simple sentence.
    Question: {question}
    Data:
    {data_sample}
    """
    query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        $$ {prompt} $$
    );
    """
    df2 = run_query(query)
    return df2.iloc[0, 0].strip()

# ---------------------------
# SENTIMENT ANALYSIS
# ---------------------------
def analyze_sentiment(text):
    prompt = f"""
    Classify the sentiment into one word:
    Positive, Neutral, or Negative.
    Review:
    {text}
    """
    query = f"""
    SELECT SNOWFLAKE.CORTEX.COMPLETE(
        'mixtral-8x7b',
        $$ {prompt} $$
    );
    """
    df = run_query(query)
    return df.iloc[0, 0].strip()

# ---------------------------
# UI
# ---------------------------
st.title("AI Data Analyst")

if "history" not in st.session_state:
    st.session_state.history = []

question = st.text_input("Ask your question")

if question:
    try:
        with st.spinner("Thinking..."):
            fast_sql = fast_path_reviews(question)

            if fast_sql:
                sql = fast_sql
                df = run_query(sql)
            else:
                sql, df = execute_with_retry(question)

            tab1, tab2, tab3 = st.tabs(["SQL", "Results", "Insight"])

            with tab1:
                st.code(sql)

            with tab2:
                st.dataframe(df)

                if df.shape == (1, 1):
                    st.metric("Result", df.iloc[0, 0])

                if len(df.columns) >= 2:
                    st.bar_chart(df.set_index(df.columns[0]))

                if "REVIEW_COMMENT_MESSAGE" in df.columns:
                    st.subheader("Sentiment Analysis")
                    sentiments = df["REVIEW_COMMENT_MESSAGE"].dropna().head(5).apply(analyze_sentiment)

                    sentiment_df = pd.DataFrame({
                        "Review": df["REVIEW_COMMENT_MESSAGE"].head(5),
                        "Sentiment": sentiments
                    })
                    st.dataframe(sentiment_df)

            with tab3:
                st.success(generate_summary(question, df))

            st.session_state.history.append((question, sql))

    except Exception as e:
        st.error(str(e))

# ---------------------------
# SIDEBAR
# ---------------------------
st.sidebar.title("History")
for q, s in reversed(st.session_state.history):
    st.sidebar.write(q)
    st.sidebar.code(s)